### ISSUE TITLE
执行部署报错

### ISSUE THREAD

**Issue by wolone** [jenkey2011/vuepress-deploy#18]
`
  /usr/bin/docker build -t 8a33c1:f6bdd04f9f2342f4abf7dc5a29dcdba6 -f "/home/runner/work/_actions/jenkey2011/vuepress-deploy/dev/Dockerfile" "/home/runner/work/_actions/jenkey2011/vuepress-deploy/dev"
  Sending build context to Docker daemon  28.67kB
  
  Step 1/11 : FROM node:14.12.0 as base
  14.12.0: Pulling from library/node
  4f250268ed6a: Pulling fs layer
  1b49aa113642: Pulling fs layer
  c159512f4cc2: Pulling fs layer
  8439168fd8dc: Pulling fs layer
  55abbc6cc158: Pulling fs layer
  e5c5821cd889: Pulling fs layer
  8cdf70a16731: Pulling fs layer
  40ba0f817ab5: Pulling fs layer
  19c9987a828c: Pulling fs layer
  8439168fd8dc: Waiting
  55abbc6cc158: Waiting
  e5c5821cd889: Waiting
  8cdf70a16731: Waiting
  40ba0f817ab5: Waiting
  19c9987a828c: Waiting
  1b49aa113642: Verifying Checksum
  1b49aa113642: Download complete
  c159512f4cc2: Verifying Checksum
  c159512f4cc2: Download complete
  4f250268ed6a: Verifying Checksum
  4f250268ed6a: Download complete
  e5c5821cd889: Verifying Checksum
  e5c5821cd889: Download complete
  8439168fd8dc: Verifying Checksum
  8439168fd8dc: Download complete
  40ba0f817ab5: Verifying Checksum
  40ba0f817ab5: Download complete
  8cdf70a16731: Verifying Checksum
  8cdf70a16731: Download complete
  19c9987a828c: Verifying Checksum
  19c9987a828c: Download complete
  55abbc6cc158: Verifying Checksum
  55abbc6cc158: Download complete
  4f250268ed6a: Pull complete
  1b49aa113642: Pull complete
  c159512f4cc2: Pull complete
  8439168fd8dc: Pull complete
  55abbc6cc158: Pull complete
  e5c5821cd889: Pull complete
  8cdf70a16731: Pull complete
  40ba0f817ab5: Pull complete
  19c9987a828c: Pull complete
  Digest: sha256:41360669532a4b660627dcd5a2c1910590827e9b9b05c634e60bdb22770f1788
  Status: Downloaded newer image for node:14.12.0
   ---> b1a278f92adb
  Step 2/11 : LABEL "com.github.actions.name"="Vuepress deploy"
   ---> Running in dad8220d55ab
  Removing intermediate container dad8220d55ab
   ---> b9d03f956754
  Step 3/11 : LABEL "com.github.actions.description"="A GitHub Action to build and deploy Vuepress sites to GitHub Pages"
   ---> Running in 351aa7caf453
  Removing intermediate container 351aa7caf453
   ---> 8257d066c0a5
  Step 4/11 : LABEL "com.github.actions.icon"="upload-cloud"
   ---> Running in 89f28c05d68f
  Removing intermediate container 89f28c05d68f
   ---> 78e844e3e20c
  Step 5/11 : LABEL "com.github.actions.color"="gray-dark"
   ---> Running in 662039a725aa
  Removing intermediate container 662039a725aa
   ---> 94eb9000eebd
  Step 6/11 : LABEL "repository"="https://github.com/jenkey2011/vuepress-deploy"
   ---> Running in 47c3aec8b72c
  Removing intermediate container 47c3aec8b72c
   ---> 41757005c8fd
  Step 7/11 : LABEL "homepage"="https://github.com/jenkey2011/vuepress-deploy"
   ---> Running in 9f29ab0d4723
  Removing intermediate container 9f29ab0d4723
   ---> de08c8adccdb
  Step 8/11 : LABEL "maintainer"="Jenkey2011 <jenkey2011@163.com>"
   ---> Running in f729eaf78960
  Removing intermediate container f729eaf78960
   ---> 5c50ffc828e8
  Step 9/11 : RUN apk add --no-cache git jq
   ---> Running in b41be24bd43b
  /bin/sh: 1: apk: not found
  The command '/bin/sh -c apk add --no-cache git jq' returned a non-zero code: 127
  
  Warning: Docker build failed with exit code 127, back off 3.812 seconds before retry.
  /usr/bin/docker build -t 8a33c1:f6bdd04f9f2342f4abf7dc5a29dcdba6 -f "/home/runner/work/_actions/jenkey2011/vuepress-deploy/dev/Dockerfile" "/home/runner/work/_actions/jenkey2011/vuepress-deploy/dev"
  Sending build context to Docker daemon  28.67kB
  
  Step 1/11 : FROM node:14.12.0 as base
   ---> b1a278f92adb
  Step 2/11 : LABEL "com.github.actions.name"="Vuepress deploy"
   ---> Using cache
   ---> b9d03f956754
  Step 3/11 : LABEL "com.github.actions.description"="A GitHub Action to build and deploy Vuepress sites to GitHub Pages"
   ---> Using cache
   ---> 8257d066c0a5
  Step 4/11 : LABEL "com.github.actions.icon"="upload-cloud"
   ---> Using cache
   ---> 78e844e3e20c
  Step 5/11 : LABEL "com.github.actions.color"="gray-dark"
   ---> Using cache
   ---> 94eb9000eebd
  Step 6/11 : LABEL "repository"="https://github.com/jenkey2011/vuepress-deploy"
   ---> Using cache
   ---> 41757005c8fd
  Step 7/11 : LABEL "homepage"="https://github.com/jenkey2011/vuepress-deploy"
   ---> Using cache
   ---> de08c8adccdb
  Step 8/11 : LABEL "maintainer"="Jenkey2011 <jenkey2011@163.com>"
   ---> Using cache
   ---> 5c50ffc828e8
  Step 9/11 : RUN apk add --no-cache git jq
   ---> Running in 8519983c54b0
  /bin/sh: 1: apk: not found
  The command '/bin/sh -c apk add --no-cache git jq' returned a non-zero code: 127
  
  Warning: Docker build failed with exit code 127, back off 1.66 seconds before retry.
  /usr/bin/docker build -t 8a33c1:f6bdd04f9f2342f4abf7dc5a29dcdba6 -f "/home/runner/work/_actions/jenkey2011/vuepress-deploy/dev/Dockerfile" "/home/runner/work/_actions/jenkey2011/vuepress-deploy/dev"
  Sending build context to Docker daemon  28.67kB
  
  Step 1/11 : FROM node:14.12.0 as base
   ---> b1a278f92adb
  Step 2/11 : LABEL "com.github.actions.name"="Vuepress deploy"
   ---> Using cache
   ---> b9d03f956754
  Step 3/11 : LABEL "com.github.actions.description"="A GitHub Action to build and deploy Vuepress sites to GitHub Pages"
   ---> Using cache
   ---> 8257d066c0a5
  Step 4/11 : LABEL "com.github.actions.icon"="upload-cloud"
   ---> Using cache
   ---> 78e844e3e20c
  Step 5/11 : LABEL "com.github.actions.color"="gray-dark"
   ---> Using cache
   ---> 94eb9000eebd
  Step 6/11 : LABEL "repository"="https://github.com/jenkey2011/vuepress-deploy"
   ---> Using cache
   ---> 41757005c8fd
  Step 7/11 : LABEL "homepage"="https://github.com/jenkey2011/vuepress-deploy"
   ---> Using cache
   ---> de08c8adccdb
  Step 8/11 : LABEL "maintainer"="Jenkey2011 <jenkey2011@163.com>"
   ---> Using cache
   ---> 5c50ffc828e8
  Step 9/11 : RUN apk add --no-cache git jq
   ---> Running in cef19685edb1
  /bin/sh: 1: apk: not found
  The command '/bin/sh -c apk add --no-cache git jq' returned a non-zero code: 127
  
Error: Docker build failed with exit code 127
`

**Comment by jenkey2011** [comment]
It seems that there is something wrong with the version of dev tag. Please use version 1.6.1 or the latest master.
```yaml
uses: jenkey2011/vuepress-deploy@master
```
看起来dev这个tag有问题，用1.61或者master吧，抱歉抱歉~

**Comment by wolone** [comment]
有没有交流群呢

**Comment by wolone** [comment]
`
node version: v14.16.1
11
npm version: 6.14.12
12
==> Start building \n yarn && yarn build
13
yarn install v1.22.5
14
info No lockfile found.
15
[1/4] Resolving packages...
16
warning vuepress-theme-antdocs > core-js@2.6.12: core-js@<3 is no longer maintained and not recommended for usage due to the number of issues. Please, upgrade your dependencies to the actual version of core-js@3.
17
warning vuepress-theme-antdocs > ant-design-vue > babel-runtime > core-js@2.6.12: core-js@<3 is no longer maintained and not recommended for usage due to the number of issues. Please, upgrade your dependencies to the actual version of core-js@3.
18
warning vuepress-theme-antdocs > docsearch.js > request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
19
warning vuepress-theme-antdocs > docsearch.js > hogan.js > mkdirp@0.3.0: Legacy versions of mkdirp are no longer supported. Please update to mkdirp 1.x. (Note that the API surface has changed to use Promises in 1.x.)
20
warning vuepress-theme-antdocs > docsearch.js > request > har-validator@5.1.5: this library is no longer supported
21
warning vuepress-theme-antdocs > vuepress-plugin-container > @vuepress/shared-utils > globby > fast-glob > micromatch > snapdragon > source-map-resolve > resolve-url@0.2.1: https://github.com/lydell/resolve-url#deprecated
22
warning vuepress-theme-antdocs > vuepress-plugin-container > @vuepress/shared-utils > globby > fast-glob > micromatch > snapdragon > source-map-resolve > urix@0.1.0: Please see https://github.com/lydell/urix#deprecated
23
warning core-js@2.6.12: core-js@<3 is no longer maintained and not recommended for usage due to the number of issues. Please, upgrade your dependencies to the actual version of core-js@3.
24
warning vuepress > @vuepress/core > chokidar@2.1.8: Chokidar 2 will break on node v14+. Upgrade to chokidar 3 with 15x less dependencies.
25
warning vuepress > @vuepress/core > webpack-dev-server > chokidar@2.1.8: Chokidar 2 will break on node v14+. Upgrade to chokidar 3 with 15x less dependencies.
26
warning vuepress > @vuepress/core > chokidar > fsevents@1.2.13: fsevents 1 will break on node v14+ and could be using insecure binaries. Upgrade to fsevents 2.
27
warning vuepress > @vuepress/theme-default > stylus > css-parse > css > urix@0.1.0: Please see https://github.com/lydell/urix#deprecated
28
warning vuepress > @vuepress/core > webpack > watchpack > watchpack-chokidar2 > chokidar@2.1.8: Chokidar 2 will break on node v14+. Upgrade to chokidar 3 with 15x less dependencies.
29
[2/4] Fetching packages...
30
warning url-loader@1.1.2: Invalid bin field for "url-loader".
31
info fsevents@1.2.13: The platform "linux" is incompatible with this module.
32
info "fsevents@1.2.13" is an optional dependency and failed compatibility check. Excluding it from installation.
33
info fsevents@2.3.2: The platform "linux" is incompatible with this module.
34
info "fsevents@2.3.2" is an optional dependency and failed compatibility check. Excluding it from installation.
35
[3/4] Linking dependencies...
36
warning "vuepress-theme-antdocs > ant-design-vue@1.7.4" has unmet peer dependency "vue@^2.6.0".
37
warning "vuepress-theme-antdocs > ant-design-vue@1.7.4" has unmet peer dependency "vue-template-compiler@^2.6.0".
38
warning "vuepress-theme-antdocs > less-loader@5.0.0" has unmet peer dependency "webpack@^2.0.0 || ^3.0.0 || ^4.0.0".
39
warning "vuepress-theme-antdocs > vuex@3.6.2" has unmet peer dependency "vue@^2.0.0".
40
warning "vuepress-theme-antdocs > ant-design-vue > @ant-design/icons-vue@2.0.0" has unmet peer dependency "vue@>=2.5.0".
41
warning "vuepress-theme-antdocs > ant-design-vue > @ant-design/icons-vue@2.0.0" has unmet peer dependency "vue-template-compiler@>=2.5.0".
42
warning " > vuepress-plugin-sitemap@2.3.1" has unmet peer dependency "chalk@^2.0.0".
43
warning " > vuepress-plugin-sitemap@2.3.1" has unmet peer dependency "commander@^2.0.0".
44
warning " > vuepress-plugin-sitemap@2.3.1" has unmet peer dependency "esm@^3.0.0".
45
[4/4] Building fresh packages...
46
success Saved lockfile.
47
Done in 31.43s.
48
yarn run v1.22.5
49
$ vuepress build docs
50
wait Extracting site metadata...
51
Error: Cannot find module '../../plugin/sidebar_contents'
52
Require stack:
53
- /github/workspace/docs/.vuepress/config/sidebar.js
54
- /github/workspace/docs/.vuepress/config.js
55
- /github/workspace/node_modules/@vuepress/core/lib/node/loadConfig.js
56
- /github/workspace/node_modules/@vuepress/core/lib/node/App.js
57
- /github/workspace/node_modules/@vuepress/core/lib/index.js
58
- /github/workspace/node_modules/vuepress/lib/registerCoreCommands.js
59
- /github/workspace/node_modules/vuepress/cli.js
60
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:880:15)
61
    at Function.Module._load (internal/modules/cjs/loader.js:725:27)
62
    at Module.require (internal/modules/cjs/loader.js:952:19)
63
    at require (internal/modules/cjs/helpers.js:88:18)
64
    at Object.<anonymous> (/github/workspace/docs/.vuepress/config/sidebar.js:3:15)
65
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
66
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
67
    at Module.load (internal/modules/cjs/loader.js:928:32)
68
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
69
    at Module.require (internal/modules/cjs/loader.js:952:19)
70
    at require (internal/modules/cjs/helpers.js:88:18)
71
    at Object.<anonymous> (/github/workspace/docs/.vuepress/config.js:37:14)
72
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
73
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
74
    at Module.load (internal/modules/cjs/loader.js:928:32)
75
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
76
error Command failed with exit code 1.
77
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
`
不知道为啥又开始报错了
我的配置如下
`
name: A TO A:GH_PAGES
on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master

    - name: Build and Deploy
      uses: jenkey2011/vuepress-deploy@master
      env:
        ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        TARGET_REPO: wolone/wolone.github.io
        TARGET_BRANCH: gh_pages
        BUILD_SCRIPT: yarn && yarn build
        BUILD_DIR: docs/.vuepress/dist/
`
